// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbn_y0B7FBCU8Y1i5JBbU5zPRCYI2roIU',
    appId: '1:69041433267:android:8415be6ea05e446a741ec6',
    messagingSenderId: '69041433267',
    projectId: 'test-d7cca',
    storageBucket: 'test-d7cca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEf9wXrAFd99ue99DuJqL46hw0XwMpFC4',
    appId: '1:69041433267:ios:97cc95949c8952a8741ec6',
    messagingSenderId: '69041433267',
    projectId: 'test-d7cca',
    storageBucket: 'test-d7cca.firebasestorage.app',
    iosBundleId: 'com.sixamtech.stackfooduser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEf9wXrAFd99ue99DuJqL46hw0XwMpFC4',
    appId: '1:69041433267:ios:97cc95949c8952a8741ec6',
    messagingSenderId: '69041433267',
    projectId: 'test-d7cca',
    storageBucket: 'test-d7cca.firebasestorage.app',
    iosBundleId: 'com.sixamtech.stackfooduser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgWkWdAZ3bcUgxW1TkpitIY2JvccA_1rc',
    appId: '1:69041433267:web:eb74d08a2990af61741ec6',
    messagingSenderId: '69041433267',
    projectId: 'test-d7cca',
    authDomain: 'test-d7cca.firebaseapp.com',
    storageBucket: 'test-d7cca.firebasestorage.app',
    measurementId: 'G-GBQ4MK6ZN1',
  );
}
